#!/bin/bash

INGRESO=$1

bash ../bin/trinity-randomwav working

TARGET=`echo $INGRESO | sed s/^.*internet//g`

firefox --new-tab "https://www.google.com/search?q=$TARGET" &

bash ../bin/trinity-message "Internet" "Buscando en google"
bash ../bin/trinity-randomwav endwork