#!/bin/bash

INGRESO=$1


TARGET=`echo $INGRESO | sed 's/\(^.*de\)//g'`

firefox --new-tab "https://www.youtube.com/results?search_query=$TARGET" &> /dev/null &

bash ./bin/trinity-message "Video" "Buscando video en youtube"
